import { MagAction, MagState } from "./magnetronGameTypes"
import { useCallback, useEffect, useState } from "react"
import * as api from "./gameServerApi"
import { gameExists } from "./gameServerApi"
import Cookies from "universal-cookie"
